apiVersion: v1
kind: Service
metadata:
  name: taxi-booking-app
  labels:
    name: taxi-booking-app
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: taxi-booking-app
  type: LoadBalancer